#!/bin/bash
echo 启动register-server...
java -jar lib/register-server-0.5.0.jar >>logs/register.log 2>&1 &
echo 启动gateway...
java -jar lib/gateway-0.5.0.jar >>logs/gateway.log 2>&1 &
echo 启动keeper-mgr...
java -jar lib/keeper-mgr-0.5.0.jar >>logs/mgr.log 2>&1 &
echo 启动keeper-service...
java -jar lib/keeper-service-0.5.0.jar >>logs/service.log 2>&1 &
echo 验证是否启动成功...
java -cp lib/dbus-keeper-auto-deploy-0.5.0-jar-with-dependencies.jar com.creditease.dbus.auto.deploy.DBusKeeperAutoDeployStart